<a href="https://colab.research.google.com/github/bhanu080/bhanu080/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Import numpy

In [1]:
import numpy as np


define a Python list containing the ages of 6 people.

In [2]:
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use np.array(<collection>)

In [3]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [4]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [5]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


Multi-dimension


define a new list containing the weights of these 6 people.

In [6]:
weight_list = [32, 18, 26, 60, 55, 65]

define an ndarray containing all fo this information, and again print the size and shape of the array.

In [7]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [8]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 
# /t --> horizontal space

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)



Note: The new shape must be the same "size" as the old shape

Exercise

In [9]:
# Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

list=[7, 9, 65, 33, 85, 99]
print(list)


[7, 9, 65, 33, 85, 99]


In [10]:
# Generate a matrix (2D numpy array) of the values:
arr=np.array([[1,2,4],  [2,3,0], [0,5,1]])
print(arr)


[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [11]:
# Change the dimensions of this array to another permitted shape
arr=np.array([[1,2,4],  [2,3,0], [0,5,1]])
print("Changing shape to 3,6")
print(arr.shape)

Changing shape to 3,6
(3, 3)


Array Generation

Instead of defining an array manually, we can ask numpy to do it for us.

The np.arange() method creates a range of numbers with user defined steps between each.

In [12]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

he np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [13]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The .repeat() method will repeat an object you pas a specified number of times.

In [14]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


The np.eye() functions will create an identity matrix/array for us.

In [15]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Operations

There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

What is happening in each line?

In [16]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


Speed Test

If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference

In [54]:
fives_list = list(range(0,5001,5))
fives_list

TypeError: ignored

In [19]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [20]:
%timeit five_times_table_lge + 5

1.35 µs ± 18.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
%timeit [e + 5 for e in fives_list]

NameError: ignored

Boolean string operations can also be performed on ndarrays.

In [22]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

Transpose

In [23]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


Data Types

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the .dtype attribute.

In [24]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [25]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')


What is the dtype of this array?

In [26]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

What do you think has happened here?

In [27]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [28]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [29]:
ages_with_strings.size

126

In [30]:
ages_with_strings.size/21

6.0

In [31]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.

In [32]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


Exercise

In [33]:
# Create an array of string numbers, but use dtype to make it an array of floats.

x = np.array(['1.2', '2.5', '3.7'])
y = x.astype(np.float)
print(y)

[1.2 2.5 3.7]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


In [34]:
#### Transpose the matrix, printing the new size and shape.

arr= np.array([[1, 2, 3], [4, 5, 6]])

print(f'Array:\n{arr}')
arr_transpose = arr.transpose()

print(f'Transposed Array:\n{arr_transpose}')
print("Size:\t" , arr.size)
print("Shape:\t", arr.shape)


Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]
Size:	 6
Shape:	 (2, 3)


In [35]:
#### Use the .astype() method to convert the array to boolean.

arr= np.array([[0,1,1], [1,0,0]])
arr.astype(np.bool)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


array([[False,  True,  True],
       [ True, False, False]])

Array Slicing Operations

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [36]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [37]:
five_times_table[0]

0

In [38]:
five_times_table[-1]

50

In [39]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [40]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [41]:
print(people)
people[:3, :3]


[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

Exercise

In [42]:
# Create a numpy array with 50 zeros
zeroArr = np.zeros(50)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [43]:
# Create a np array of 2 repeated 20 times

twoArr = np.repeat(2, 20)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [44]:
# Create a numpy array from 0 to 2pi  in steps of 0.1
import math as m
space=np.arange(0,m.pi*2,0.1)
print(space)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]


In [45]:
# For one of the arrays generated:

# Get the first five values
# Get the last 3 values
# Get the 4th value to the 7th value

five_times_table
print(five_times_table)
five_times_table[:5]
five_times_table[8:]
five_times_table[4:7]

[ 0  5 10 15 20 25 30 35 40 45 50]


array([20, 25, 30])

Stats

In [46]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [47]:
nums = np.arange(0, 4, 0.2555)
print(nums)

[0.     0.2555 0.511  0.7665 1.022  1.2775 1.533  1.7885 2.044  2.2995
 2.555  2.8105 3.066  3.3215 3.577  3.8325]


Exercise

In [48]:
#Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))


min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


Random

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [49]:
flip = np.random.choice([0,1], 10)
flip

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1])

In [50]:
np.random.rand(10,20,9)

array([[[0.95286926, 0.86691276, 0.97644084, ..., 0.87031258,
         0.97087143, 0.98109707],
        [0.21775111, 0.62883488, 0.22054627, ..., 0.40413353,
         0.80628104, 0.85411242],
        [0.03633246, 0.21924512, 0.60954834, ..., 0.53165084,
         0.56309509, 0.70281862],
        ...,
        [0.18077252, 0.61670598, 0.91530292, ..., 0.68264139,
         0.41848684, 0.71866229],
        [0.82138393, 0.88737602, 0.81279979, ..., 0.01333406,
         0.87217767, 0.21253087],
        [0.61049473, 0.81548532, 0.3995332 , ..., 0.56056749,
         0.79160355, 0.25629657]],

       [[0.65349447, 0.00617737, 0.17634084, ..., 0.14287215,
         0.72435398, 0.39145847],
        [0.27916017, 0.57833231, 0.14911763, ..., 0.18994186,
         0.26509924, 0.57930507],
        [0.0528823 , 0.29349746, 0.39598409, ..., 0.97794643,
         0.5480041 , 0.04530326],
        ...,
        [0.4683461 , 0.77158763, 0.62072276, ..., 0.45383742,
         0.00417516, 0.5087458 ],
        [0.7

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

In [51]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
print(s)

[-6.53663413e-02  3.84514044e-02 -6.60083508e-02  7.35535450e-02
 -2.89217746e-02 -6.41348135e-03  4.00731028e-02 -7.60916502e-02
 -1.24820292e-01  2.02895236e-01 -2.53612477e-02  3.97055006e-02
  7.93810963e-02  6.83465268e-02 -1.23747942e-02 -1.97819963e-01
  9.04834644e-02 -7.91429136e-02 -2.27914364e-02  1.41581822e-02
 -1.63706060e-01  1.69245808e-01  7.50269684e-03  1.88527346e-01
 -1.28576914e-02 -9.49484066e-02 -3.31197761e-03  3.81485407e-03
  1.10756004e-01 -7.46196025e-02 -1.09994321e-02  5.04969615e-02
 -1.06951287e-01  3.06645435e-02  1.14657133e-01 -4.54235279e-03
 -1.61105034e-02 -4.86822721e-02  3.10142487e-02 -6.06727498e-02
 -1.71791632e-02 -1.35563921e-01 -6.07553073e-02  5.59878194e-02
  1.05928736e-01 -1.36176074e-01 -9.81691093e-02 -9.27618005e-02
  2.34574480e-01  9.60148292e-02 -3.78043150e-02 -1.36078156e-01
 -1.60638510e-01 -2.70462098e-02  1.31824079e-02  7.13059726e-02
 -1.19708488e-01  2.93588817e-02 -1.14345079e-01 -8.96803452e-02
 -9.07727323e-02 -1.60116

Exercise

In [52]:
 # Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

flip = np.random.choice([1,2,3,4,5,6], 10)
flip

array([6, 5, 6, 5, 3, 1, 5, 3, 4, 2])

In [55]:
# Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

coin_throw = np.random.choice(['Head',"Head",'Tail'],2)
coin_throw

array(['Head', 'Head'], dtype='<U4')